### ISSUE TITLE
Add @ClosureParams annotations as appropriate

### ISSUE THREAD

**Issue by mhurne** [commercehub-oss/griddle#11]

**Comment by mhurne** [comment]
Turns out this will require a Groovy upgrade, as `@ClosureParams ` isn't present in Groovy 2.2.1. @davidmc24: Should we bump the major version as a result?

**Comment by davidmc24** [comment]
@mhurne yeah, let's bump the major version of griddle.

**Comment by davidmc24** [comment]
That would be 3.0.0 as the new version.

**Comment by mhurne** [comment]
Ok, version has been bumped to 3.0.0.

**Comment by davidmc24** [comment]
@mhurne Do you want to handle this release, or shall I?

**Comment by mhurne** [comment]
@davidmc24 I don't mind handling it.

**Comment by davidmc24** [comment]
@mhurne  Go for it :) :+1:
