### ISSUE TITLE
Consider replacing use of opencsv with an alternative

### ISSUE THREAD

**Issue by mhurne** [commercehub-oss/griddle#9]
opencsv seems stagnant, and doesn't appear to claim compliance with RFC 4180 (one source that agrees: http://csveed.org/comparison-matrix.html). There are alternatives that are both active and claim RFC 4180 compliance, such as Super CSV (see http://super-csv.github.io/super-csv/csv_specification.html). I think it'd be wise to replace usage of opencsv with one of the alternatives.

**Comment by mdbouchard** [comment]
Matt, we've used Super CSV in ConnMgr for a bulk contracts import.

**Comment by mhurne** [comment]
Good to know - how do you like it?

**Comment by mdbouchard** [comment]
It's not bad. The validation is exception based. If you have more than one failure on a line, you only get the first one. The error messages aren't UI friendly either so we have overridden many of those validators.

**Comment by davidmc24** [comment]
Fine by me. Feel like contributing a pull request?

**Comment by mhurne** [comment]
Absolutely
